### ISSUE TITLE
Errors with Strapi 4.4.3

### ISSUE THREAD

**Issue by djmtype** [dasmikko/strapi-tiptap-editor#41]
There are 2 major errors after installing this plugin that prevent me from reaching the content modeling area of Strapi. 

```
main.de2e0941.js:9535 TypeError: Property description must be an object: -
    at defineProperties (<anonymous>)
    at i (main.de2e0941.js:24:32388)
    at t (main.de2e0941.js:9008:24884)
    at r (main.de2e0941.js:9008:21485)
    at cs (content-type-builder.17529402.chunk.js:788:21117)
    at e5 (main.de2e0941.js:9533:54803)
    at N3 (main.de2e0941.js:9537:9232)
    at D3 (main.de2e0941.js:9537:992)
    at n6 (main.de2e0941.js:9537:920)
    at g5 (main.de2e0941.js:9537:771)
D5 @ main.de2e0941.js:9535
main.de2e0941.js:9565 Uncaught TypeError: Property description must be an object: -
    at defineProperties (<anonymous>)
    at i (main.de2e0941.js:24:32388)
    at t (main.de2e0941.js:9008:24884)
    at r (main.de2e0941.js:9008:21485)
    at cs (content-type-builder.17529402.chunk.js:788:21117)
    at e5 (main.de2e0941.js:9533:54803)
    at N3 (main.de2e0941.js:9537:9232)
    at D3 (main.de2e0941.js:9537:992)
    at n6 (main.de2e0941.js:9537:920)
    at g5 (main.de2e0941.js:9537:771)
```

**Comment by djmtype** [comment]
This plugin had a conflict with another plugin.
