### ISSUE TITLE
Not working with strapi v4.5.6

### ISSUE THREAD

**Issue by martenb** [dasmikko/strapi-tiptap-editor#56]
i cannot even build the app...

npm run build
fails

**Comment by dasmikko** [comment]
I need some logs, to be able to help

**Comment by martenb** [comment]
```
#0 0.428 yarn run v1.22.19                                                                                                          
#0 0.451 $ strapi build                                                                                                             
#0 1.963 Building your admin UI with development configuration...
#0 2.444 ℹ Compiling Webpack
#0 5.884 ModuleNotFoundError: Module not found: Error: Can't resolve 'prosemirror-history' in '/opt/app/node_modules/@tiptap/extension-history/dist'
#0 5.884     at /opt/app/node_modules/webpack/lib/Compilation.js:2016:28
#0 5.884     at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:798:13
#0 5.884     at eval (eval at create (/opt/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
#0 5.884     at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:270:22
#0 5.884     at eval (eval at create (/opt/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
#0 5.884     at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:434:22
#0 5.884     at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:116:11
#0 5.884     at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:670:25
#0 5.884     at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:855:8
#0 5.884     at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:975:5
#0 5.884 resolve 'prosemirror-history' in '/opt/app/node_modules/@tiptap/extension-history/dist'
#0 5.884   Parsed request is a module
#0 5.884   using description file: /opt/app/node_modules/@tiptap/extension-history/package.json (relative path: ./dist)
#0 5.884     Field 'browser' doesn't contain a valid alias configuration
#0 5.884     resolve as module
#0 5.884       /opt/app/node_modules/@tiptap/extension-history/dist/node_modules doesn't exist or is not a directory
#0 5.884       /opt/app/node_modules/@tiptap/extension-history/node_modules doesn't exist or is not a directory
#0 5.884       /opt/app/node_modules/@tiptap/node_modules doesn't exist or is not a directory
#0 5.884       /opt/app/node_modules/node_modules doesn't exist or is not a directory
#0 5.884       looking for modules in /opt/app/node_modules
#0 5.884         single file module
#0 5.884           using description file: /opt/app/package.json (relative path: ./node_modules/prosemirror-history)
#0 5.884             no extension
#0 5.884               Field 'browser' doesn't contain a valid alias configuration
#0 5.884               /opt/app/node_modules/prosemirror-history doesn't exist
#0 5.884             .js
#0 5.884               Field 'browser' doesn't contain a valid alias configuration
#0 5.884               /opt/app/node_modules/prosemirror-history.js doesn't exist
#0 5.884             .jsx
#0 5.884               Field 'browser' doesn't contain a valid alias configuration
#0 5.884               /opt/app/node_modules/prosemirror-history.jsx doesn't exist
#0 5.884             .react.js
#0 5.884               Field 'browser' doesn't contain a valid alias configuration
#0 5.884               /opt/app/node_modules/prosemirror-history.react.js doesn't exist
#0 5.884             .ts
#0 5.884               Field 'browser' doesn't contain a valid alias configuration
#0 5.884               /opt/app/node_modules/prosemirror-history.ts doesn't exist
#0 5.884             .tsx
#0 5.884               Field 'browser' doesn't contain a valid alias configuration
#0 5.884               /opt/app/node_modules/prosemirror-history.tsx doesn't exist
#0 5.884         /opt/app/node_modules/prosemirror-history doesn't exist
#0 5.884       /opt/node_modules doesn't exist or is not a directory
#0 5.884       /node_modules doesn't exist or is not a directory
#0 5.884       looking for modules in /opt/app/node_modules/@strapi/admin/node_modules
#0 5.884         single file module
#0 5.884           using description file: /opt/app/node_modules/@strapi/admin/package.json (relative path: ./node_modules/prosemirror-history)
#0 5.884             no extension
#0 5.884               Field 'browser' doesn't contain a valid alias configuration
#0 5.884               /opt/app/node_modules/@strapi/admin/node_modules/prosemirror-history doesn't exist
#0 5.884             .js
#0 5.884               Field 'browser' doesn't contain a valid alias configuration
#0 5.884               /opt/app/node_modules/@strapi/admin/node_modules/prosemirror-history.js doesn't exist
#0 5.884             .jsx
#0 5.884               Field 'browser' doesn't contain a valid alias configuration
#0 5.884               /opt/app/node_modules/@strapi/admin/node_modules/prosemirror-history.jsx doesn't exist
#0 5.884             .react.js
#0 5.884               Field 'browser' doesn't contain a valid alias configuration
#0 5.884               /opt/app/node_modules/@strapi/admin/node_modules/prosemirror-history.react.js doesn't exist
#0 5.884             .ts
#0 5.884               Field 'browser' doesn't contain a valid alias configuration
#0 5.884               /opt/app/node_modules/@strapi/admin/node_modules/prosemirror-history.ts doesn't exist
#0 5.884             .tsx
#0 5.884               Field 'browser' doesn't contain a valid alias configuration
#0 5.884               /opt/app/node_modules/@strapi/admin/node_modules/prosemirror-history.tsx doesn't exist
#0 5.884         /opt/app/node_modules/@strapi/admin/node_modules/prosemirror-history doesn't exist
#0 5.892 ModuleNotFoundError: Module not found: Error: Can't resolve 'prosemirror-history' in '/opt/app/node_modules/@tiptap/extension-history/dist'
#0 5.892     at /opt/app/node_modules/webpack/lib/Compilation.js:2016:28
#0 5.892     at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:798:13
#0 5.892     at eval (eval at create (/opt/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
#0 5.892     at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:270:22
#0 5.892     at eval (eval at create (/opt/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
#0 5.892     at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:434:22
#0 5.892     at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:116:11
#0 5.892     at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:670:25
#0 5.892     at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:855:8
#0 5.892     at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:975:5
#0 5.892 resolve 'prosemirror-history' in '/opt/app/node_modules/@tiptap/extension-history/dist'
#0 5.892   Parsed request is a module
#0 5.892   using description file: /opt/app/node_modules/@tiptap/extension-history/package.json (relative path: ./dist)
#0 5.892     Field 'browser' doesn't contain a valid alias configuration
#0 5.892     resolve as module
#0 5.892       /opt/app/node_modules/@tiptap/extension-history/dist/node_modules doesn't exist or is not a directory
#0 5.892       /opt/app/node_modules/@tiptap/extension-history/node_modules doesn't exist or is not a directory
#0 5.892       /opt/app/node_modules/@tiptap/node_modules doesn't exist or is not a directory
#0 5.892       /opt/app/node_modules/node_modules doesn't exist or is not a directory
#0 5.892       looking for modules in /opt/app/node_modules
#0 5.892         single file module
#0 5.892           using description file: /opt/app/package.json (relative path: ./node_modules/prosemirror-history)
#0 5.892             no extension
#0 5.892               Field 'browser' doesn't contain a valid alias configuration
#0 5.892               /opt/app/node_modules/prosemirror-history doesn't exist
#0 5.892             .js
#0 5.892               Field 'browser' doesn't contain a valid alias configuration
#0 5.892               /opt/app/node_modules/prosemirror-history.js doesn't exist
#0 5.892             .jsx
#0 5.892               Field 'browser' doesn't contain a valid alias configuration
#0 5.892               /opt/app/node_modules/prosemirror-history.jsx doesn't exist
#0 5.892             .react.js
#0 5.892               Field 'browser' doesn't contain a valid alias configuration
#0 5.892               /opt/app/node_modules/prosemirror-history.react.js doesn't exist
#0 5.892             .ts
#0 5.892               Field 'browser' doesn't contain a valid alias configuration
#0 5.892               /opt/app/node_modules/prosemirror-history.ts doesn't exist
#0 5.892             .tsx
#0 5.892               Field 'browser' doesn't contain a valid alias configuration
#0 5.892               /opt/app/node_modules/prosemirror-history.tsx doesn't exist
#0 5.892         /opt/app/node_modules/prosemirror-history doesn't exist
#0 5.892       /opt/node_modules doesn't exist or is not a directory
#0 5.892       /node_modules doesn't exist or is not a directory
#0 5.892       looking for modules in /opt/app/node_modules/@strapi/admin/node_modules
#0 5.892         single file module
#0 5.892           using description file: /opt/app/node_modules/@strapi/admin/package.json (relative path: ./node_modules/prosemirror-history)
#0 5.892             no extension
#0 5.892               Field 'browser' doesn't contain a valid alias configuration
#0 5.892               /opt/app/node_modules/@strapi/admin/node_modules/prosemirror-history doesn't exist
#0 5.892             .js
#0 5.892               Field 'browser' doesn't contain a valid alias configuration
#0 5.892               /opt/app/node_modules/@strapi/admin/node_modules/prosemirror-history.js doesn't exist
#0 5.892             .jsx
#0 5.892               Field 'browser' doesn't contain a valid alias configuration
#0 5.892               /opt/app/node_modules/@strapi/admin/node_modules/prosemirror-history.jsx doesn't exist
#0 5.892             .react.js
#0 5.892               Field 'browser' doesn't contain a valid alias configuration
#0 5.892               /opt/app/node_modules/@strapi/admin/node_modules/prosemirror-history.react.js doesn't exist
#0 5.892             .ts
#0 5.892               Field 'browser' doesn't contain a valid alias configuration
#0 5.892               /opt/app/node_modules/@strapi/admin/node_modules/prosemirror-history.ts doesn't exist
#0 5.892             .tsx
#0 5.892               Field 'browser' doesn't contain a valid alias configuration
#0 5.892               /opt/app/node_modules/@strapi/admin/node_modules/prosemirror-history.tsx doesn't exist
#0 5.892         /opt/app/node_modules/@strapi/admin/node_modules/prosemirror-history doesn't exist
#0 5.924 error Command failed with exit code 1.
#0 5.924 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by NLGRF** [comment]
@martenb 
I found same problem in strapi 4.5.6 . but, this problem still found tiptap/react since version 2.0.0-beta.xxx to present
- solution to fixbug
`
yarn add prosemirror-schema-list prosemirror-history prosemirror-dropcursor prosemirror-gapcursor prosemirror-keymap prosemirror-commands
`

**Comment by onexdata** [comment]
Tried this with Strapi 4.5.6, Node 14.20.0, Windows 10, Yarn 1.22.19, the solution by @NLGRF doesn't fix the error with this configuation.

**Comment by diego06884** [comment]
After installing the dependencies, Strapi throws this error when opening the editor: RangeError: Adding different instances of a keyed plugin (plugin$)
Any progress on this?
