### ISSUE TITLE
TypeError: webpack.NormalModuleReplacementPlugin is not a constructor

### ISSUE THREAD

**Issue by philohelp** [dasmikko/strapi-tiptap-editor#71]
Happened when updating to strapi v4.15.5

Maybe related to this
https://stackoverflow.com/questions/68106588/typeerror-webpack-defineplugin-is-not-a-constructor

**Comment by DespertaWeb** [comment]
Yep! Just as @philohelp  referenced above, do this:

remove your webpack as param and require it:
```
const webpack = require("webpack");
```

**Comment by MakotoPD** [comment]
i have same issuse,

terminal error:
```
⠼ Creating admin/www/denalify-backend/src/admin/webpack.config.js:7
    config.plugins.push(new webpack.NormalModuleReplacementPlugin(
                        ^


TypeError: webpack2.NormalModuleReplacementPlugin is not a constructor
    at module.exports (/www/denalify-backend/src/admin/webpack.config.js:7:25)
    at Object.mergeConfigWithUserConfig (/www/denalify-backend/node_modules/@strapi/admin/_internal/node/webpack/config.ts:209:14)
    at <anonymous> (/www/denalify-backend/node_modules/@strapi/admin/_internal/node/webpack/build.ts:11:25)

Node.js v20.12.1
```

webpack.config.js:
```
'use strict';
/* eslint-disable no-unused-vars */
module.exports = (config, webpack) => {
    // Note: we provide webpack above so you should not `require` it
     // Perform customizations to webpack configuration
    config.plugins.push(new webpack.NormalModuleReplacementPlugin(
      /^tippy\.js$/,
      'tippy.js/dist/tippy-bundle.umd.min.js'
    ))
    // Important: return the modified configuration  
    return config;
};
```

But when I remove the code from `webpack.config.js` strapi runs, in the settings I see STRAPI TIPTAP EDITOR, but I cannot use it in the content-type builder..

**Comment by MakotoPD** [comment]
@philohelp  or just remove this code
```
config.plugins.push(new webpack.NormalModuleReplacementPlugin(
  /^tippy\.js$/,
  'tippy.js/dist/tippy-bundle.umd.min.js'
))
```
from `webpack.config.js` and now will work..

**Comment by joaoprcosta** [comment]
> Yep! Just as @philohelp referenced above, do this:
> 
> remove your webpack as param and require it:
> 
> ```
> const webpack = require("webpack");
> ```

After doing this it returns another error:
"Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema."
