### ISSUE TITLE
Support for Strapi v5

### ISSUE THREAD

**Issue by verdverm** [dasmikko/strapi-tiptap-editor#74]
v5 is in beta now, any plans to support upgrade?

I'm getting the following error

```
✖ Building admin panel
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                               │
│   RollupError: [commonjs--resolver] Expression expected in                                                                                    │
│   /Users/tony/ts/services/strapi/node_modules/@_sh/strapi-plugin-ckeditor/admin/src/components/CKEditorIcon.js                                │
│   file: /Users/tony/ts/services/strapi/node_modules/@_sh/strapi-plugin-ckeditor/admin/src/components/CKEditorIcon.js:15:2                     │
│   13:                                                                                                                                         │
│   14: const SvgIcon = () => (                                                                                                                 │
│   15:   <svg                                                                                                                                  │
│   ^                                                                                                                                           │
│   16:   width="68"                                                                                                                            │
│   17:   height="64"                                                                                                                           │
│   at getRollupError (file:///Users/tony/ts/services/strapi/node_modules/rollup/dist/es/shared/parseAst.js:376:41)                             │
│   at convertProgram (file:///Users/tony/ts/services/strapi/node_modules/rollup/dist/es/shared/parseAst.js:1040:26)                            │
│   at parseAst (file:///Users/tony/ts/services/strapi/node_modules/rollup/dist/es/shared/parseAst.js:2182:12)                                  │
│   at tryParse (file:///Users/tony/ts/services/strapi/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:7666:12)                              │
│   at analyzeTopLevelStatements (file:///Users/tony/ts/services/strapi/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:7686:15)             │
│   at Object.transformAndCheckExports (file:///Users/tony/ts/services/strapi/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:9734:68)       │
│   at Object.transform (file:///Users/tony/ts/services/strapi/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:9934:41)                      │
│   at file:///Users/tony/ts/services/strapi/node_modules/rollup/dist/es/shared/node-entry.js:19595:40                                          │
│                                                                                                                                               │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
error Command failed with exit code 1.

```

**Comment by sadeq-qafari** [comment]
any updates on this?

**Comment by ramazansancar** [comment]
Same issue
