### ISSUE TITLE
Error on strapi V5 . Strapi v5 does not support tip tap editor ?

### ISSUE THREAD

**Issue by duru015** [dasmikko/strapi-tiptap-editor#77]
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                                               │
│   [commonjs--resolver] Expression expected in /Users/durgadhakal/Desktop/Tuki Project/fasyl-backend/node_modules/strapi-tiptap-editor/admin/src/components/Wysiwyg/index.js   │
│   file: /Users/durgadhakal/Desktop/Tuki Project/fasyl-backend/node_modules/strapi-tiptap-editor/admin/src/components/Wysiwyg/index.js:59:4                                    │
│                                                                                                                                                                               │
│   57:                                                                                                                                                                         │
│   58:   return (                                                                                                                                                              │
│   59:     <WysiwygContent                                                                                                                                                     │
│           ^                                                                                                                                                                   │
│   60:       name={name}                                                                                                                                                       │
│   61:       onChange={onChange}                                                                                                                                               │
│                                                                                                                                                                               │
│       at getRollupError (file:///Users/durgadhakal/Desktop/Tuki%20Project/fasyl-backend/node_modules/rollup/dist/es/shared/parseAst.js:395:41)                                │
│       at convertProgram (file:///Users/durgadhakal/Desktop/Tuki%20Project/fasyl-backend/node_modules/rollup/dist/es/shared/parseAst.js:1083:26)                               │
│       at parseAst (file:///Users/durgadhakal/Desktop/Tuki%20Project/fasyl-backend/node_modules/rollup/dist/es/shared/parseAst.js:2068:87)                                     │
│       at tryParse (file:///Users/durgadhakal/Desktop/Tuki%20Project/fasyl-backend/node_modules/vite/dist/node/chunks/dep-p3C6MpSJ.js:7687:12)                                 │
│       at analyzeTopLevelStatements (file:///Users/durgadhakal/Desktop/Tuki%20Project/fasyl-backend/node_modules/vite/dist/node/chunks/dep-p3C6MpSJ.js:7707:15)                │
│       at Object.transformAndCheckExports (file:///Users/durgadhakal/Desktop/Tuki%20Project/fasyl-backend/node_modules/vite/dist/node/chunks/dep-p3C6MpSJ.js:9760:68)          │
│       at Object.transform (file:///Users/durgadhakal/Desktop/Tuki%20Project/fasyl-backend/node_modules/vite/dist/node/chunks/dep-p3C6MpSJ.js:9960:41)                         │
│       at file:///Users/durgadhakal/Desktop/Tuki%20Project/fasyl-backend/node_modules/rollup/dist/es/shared/node-entry.js:20730:40

**Comment by zinni0** [comment]
There is at the moment no support for Strapi v5 and above as seen in #74

**Comment by SalahAdDin** [comment]
> There is at the moment no support for Strapi v5 and above as seen in [#74](https://github.com/dasmikko/strapi-tiptap-editor/issues/74)

Do you have any alternative plugin?

**Comment by zinni0** [comment]
> > There is at the moment no support for Strapi v5 and above as seen in [#74](https://github.com/dasmikko/strapi-tiptap-editor/issues/74)
> 
> Do you have any alternative plugin?

We used the build in "Rich Text (Blocks)" for the project. We didn´t need the full possibilities of an actual RichText Editor, so it worked for us by customised the frontend.

It´s been a while since I worked with Strapi v5, so maybe there are some new plugins or this editor has an update.

**Comment by SalahAdDin** [comment]
> > > There is at the moment no support for Strapi v5 and above as seen in [#74](https://github.com/dasmikko/strapi-tiptap-editor/issues/74)
> > 
> > 
> > Do you have any alternative plugin?
> 
> We used the build in "Rich Text (Blocks)" for the project. We didn´t need the full possibilities of an actual RichText Editor, so it worked for us by customised the frontend.
> 
> It´s been a while since I worked with Strapi v5, so maybe there are some new plugins or this editor has an update.

Nope, there are not good alternatives, and no one is working on them.

Any Strapi alternative?
